Savva Dzhumaliev Mock 1
EasileleM/gd-ui-internship-mocks pull request #1
Opened 2019-09-27 19:09 UTC by EasileleM

2019-09-27 19:13 UTC, EasileleM commented
https://savva-dzhumaliev-task1.firebaseapp.com/

2019-09-30 10:43 UTC, vadeneev requested changes

2019-09-30 10:43 UTC, vadeneev commented on doc1/public/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1">
There should be better place for viewport meta tag

2019-09-30 10:43 UTC, vadeneev commented on doc1/public/index.html
> +<html>
check this one https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang

2019-09-30 10:43 UTC, vadeneev commented on doc1/public/index.html
> +        <header class="container header">
From my point of view - 'container' is so indistinct and too general name for block, doesn't it look so for you?

2019-09-30 10:43 UTC, vadeneev commented on doc1/public/index.html
> +                <h1 class="container_header-text header__text-block_header-text">Working <br> with design lab</h1>
It is not good practice to use element of parent's block inside its children:
https://ru.bem.info/methodology/key-concepts/#%D0%B1%D0%BB%D0%BE%D0%BA

2019-09-30 10:43 UTC, vadeneev commented on doc1/public/index.html
> +          <div class="container__border-text-block container__border-text-block_black about-us">
how about container__text-block_bordered ?
and what is text-block here, maybe it is an article ?

2019-09-30 10:43 UTC, vadeneev commented on doc1/public/index.html
> +                <p class="container_text header__text-block_text">
text-block_text ?

Is text modifier here ?

2019-09-30 10:43 UTC, vadeneev commented on doc1/public/index.html
> +            <h2 class="container_header-text container_header-text-black">About us</h2>
black inside black - probably smth went wrong  for this moment

2019-09-30 10:43 UTC, vadeneev commented on doc1/public/index.html
> +                <h2 class="container_header-text container_header-text-white">Services</h2>
white inside white

2019-09-30 10:43 UTC, vadeneev commented on doc1/public/index.html
> +                <p class="container_text what-we-do__text">
So we are mixing two entities on one html's top level entity, there should be better way to achieve desired result

2019-09-30 10:43 UTC, vadeneev commented on doc1/public/index.html
> +                  <a href="#" class="our-works_topworkz-image our-works_lable"></a>
Maybe label ?

2019-09-30 10:43 UTC, vadeneev commented on doc1/public/style/style.css
> +  font-size: 3.15vh;
It is great way to achieve responsive behavior, however: 
![image](https://user-images.githubusercontent.com/8614249/65871975-9b313580-e390-11e9-8d20-56670f0f9c61.png)

it what was not expected, or am i wrong ?

2019-10-01 15:59 UTC, EasileleM commented on doc1/public/style/style.css
> +  font-size: 3.15vh;
I'm wrong here, ty

2019-10-04 08:15 UTC, vadeneev requested changes

2019-10-04 08:15 UTC, vadeneev commented on doc1/public/index.html
> +      <h1 class="header__text-block_main-bottom">with design lab</h1>
We should not use more then one h1 tag - it is recommended to follow this rule, as far as h1 is one and most important on the page

2019-10-04 08:15 UTC, vadeneev commented on doc1/public/index.html
> +    <div class="section__text-block section__text-block_bordered-black">
black / white - ok, what if tomorrow UX team will tell you to start use dark/light gray instead ?

2019-10-04 08:15 UTC, vadeneev commented on doc1/public/index.html
> +      <article class="section__article section__article_abous-us-top">
article supposed and recommended to have header https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article
In that particular case articles applied incorrectly

2019-10-04 08:15 UTC, vadeneev commented on doc1/public/index.html
> +      <article class="section__article section__article_services-top">
So what is modifier means here ? services-top mean it should be on top position, mean position_top ?

2019-10-04 08:15 UTC, vadeneev commented on doc1/public/index.html
> +    <div class="section__text-block section__text-block_bordered-black section__text-block_what-we-do">
Why is that block so special, that it has modifier _what-we-do ?

2019-10-08 07:35 UTC, vadeneev requested changes

2019-10-08 07:35 UTC, vadeneev commented on doc1/public/index.html
> +      <p class="section__article section__article_abous-us section__article_abous-us-position-bottom">
abous-us ?

2019-10-08 07:35 UTC, vadeneev commented on doc1/public/index.html
> +      <h3 class="section__header section__header_what-we-do">What we do</h3>
Are you sure that it is fine name for modifier ?

2019-10-08 11:15 UTC, vadeneev requested changes

2019-10-08 11:15 UTC, vadeneev commented on doc1/public/index.html
> +    <div class="section__text-block section__text-block_bordered-black">
Not sure that this one was resolved

2019-10-08 12:55 UTC, alexkond requested changes

2019-10-08 12:55 UTC, alexkond commented on doc1/public/index.html
> +      <p class="section__article section__article_services section__article_position-top">
Can't find usage of "section__article_services" class in CSS, looks like it's obsolete

2019-10-08 12:55 UTC, alexkond commented on doc1/public/index.html
> +  <section class="section section_services">
Can't find usage of "section_services" class in CSS, looks like it's obsolete

2019-10-08 12:55 UTC, alexkond commented on doc1/public/style/style.css
> +.section__text-block {
You have a rule for ".section__text-block" class right above and it partially does the same things like this one.

2019-10-08 12:55 UTC, alexkond commented on doc1/public/style/style.css
> +.section__text-block_bordered-secondary-color {
This class changes not only borders but color also, consider renaming it.

2019-10-08 13:04 UTC, EasileleM commented on doc1/public/index.html
> +      <p class="section__article section__article_services section__article_position-top">
It sets up background image to this section.

2019-10-08 13:04 UTC, EasileleM commented on doc1/public/index.html
> +  <section class="section section_services">
section_services

2019-10-08 13:05 UTC, EasileleM commented on doc1/public/index.html
> +  <section class="section section_services">
It sets up background image to this section

2019-10-08 13:49 UTC, vovcyan submitted a review, later dismissed

2019-10-09 05:35 UTC, alexkond submitted a review, later dismissed

2019-10-09 06:50 UTC, vadeneev approved these changes

2019-10-09 07:04 UTC, vovcyan approved these changes

2019-10-09 07:10 UTC, merged