Savva Dzhumaliev Mock 2
EasileleM/gd-ui-internship-mocks pull request #3
Opened 2019-10-06 18:51 UTC by EasileleM

2019-10-06 18:52 UTC, EasileleM commented
Work in progress https://savva-dzhumaliev-task2.firebaseapp.com/

2019-10-08 12:16 UTC, vadeneev requested changes

2019-10-08 12:16 UTC, vadeneev commented on doc2/public/index.html
> +      <input type="checkbox" id="header__menu-data">
Apparently id should not be in BEM, it is more common to use camelCase for this one

2019-10-08 12:16 UTC, vadeneev commented on doc2/public/index.html
> +          <a href="#" class="section__link">Photodiary</a>
I was sure, that this one is not a link, but is smth like extra info / category

2019-10-08 12:16 UTC, vadeneev commented on doc2/public/index.html
> +          <a href="#" class="section__header-wrapper">
Bad way - because your link is whole width of h2 - no matter how much text is there.
It is strongly recommended to keep your link fit to your content

2019-10-08 12:16 UTC, vadeneev commented on doc2/public/index.html
> +        <a href="#" class="section__image-wrapper"><img src="assets/images/1.png" alt="two women in sunglasses"
So, image and title - are different links ?
Mean, i hover over image, and it has visual feedback, same for title - looks like they would navigate you to different resources.

2019-10-08 12:16 UTC, vadeneev commented on doc2/public/index.html
> +      <nav class="menu">
Totally dislike how it works in mobile view 😢

2019-10-09 13:24 UTC, vadeneev requested changes

2019-10-09 13:24 UTC, vadeneev commented on doc2/public/assets/images/arrow.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
svgminify.com clean it up

2019-10-09 13:24 UTC, vadeneev commented on doc2/private/style/footer/footer.scss
> +  flex-grow: 1;
block in BEM should not contain any kind of rules, which will define it's outer presentation (in exception case - strict size)

2019-10-09 13:24 UTC, vadeneev commented on doc2/private/style/footer/footer.scss
> +    font-size: 14px;
lets store font size in variables as well

2019-10-09 13:24 UTC, vadeneev commented on doc2/private/style/footer/footer.scss
> +    line-height: 24px;
lets store line-height in variables as well, ex. typography.scss

2019-10-09 13:24 UTC, vadeneev commented on doc2/private/style/header/header.scss
> +  #headerMenuData {
BEM doesn't use tag and ID selectors

2019-10-09 13:24 UTC, vadeneev commented on doc2/private/style/header/header.scss
> +  .menu {
Let's store it in separate file (as each block)

2019-10-09 13:24 UTC, vadeneev commented on doc2/private/style/subscribe/subscribe.scss
> +@mixin subscribe() {
wait, you is doing it wrong, why not to use simple import ? Why do we need mixin ?

2019-10-09 13:26 UTC, vadeneev requested changes

2019-10-09 13:26 UTC, vadeneev commented on doc2/private/style/main/main.scss
> +  @include block-sections();
Why are you doing this ? We could import this blocks, we don't have to include them

2019-10-09 13:31 UTC, alexkond commented on doc2/private/style/footer/footer.scss
> +    line-height: 24px;
I'd recommend creating mixins with typography related stuff.

2019-10-10 13:15 UTC, vadeneev commented on doc2/private/style/header/header.scss
> +    font-size: $header-mobile-menu-close-button-font-size;
👀

2019-10-15 17:23 UTC, akimovaa approved these changes

2019-10-16 11:48 UTC, vovcyan approved these changes

2019-10-16 18:49 UTC, merged